version: '3.8'

services:
  backend:
    build:
      context: ./data/ya-paperswithcode-database
      dockerfile: Dockerfile
    container_name: ya-pwc-backend
    ports:
      - "8000:8000"
    volumes:
      # Mount database and data files
      - ./data/ya-paperswithcode-database:/app:ro
      - backend-data:/app/data
      - backend-logs:/app/logs
      - backend-embeddings:/app/embeddings
      - backend-exports:/app/exports
    environment:
      - PYTHONPATH=/app
      - DB_PATH=/app/paperswithcode.db
    networks:
      - ya-paperswithcode-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build:
      context: ./frontend/ya-paperswithcode
      dockerfile: Dockerfile
    container_name: ya-pwc-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - ya-paperswithcode-network
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://backend:8000/api/v1

networks:
  ya-paperswithcode-network:
    driver: bridge

volumes:
  backend-data:
  backend-logs:
  backend-embeddings:
  backend-exports: